### ISSUE TITLE
Use an elliptic brush

### ISSUE THREAD

**Issue by maarzt** [juglab/labkit-ui#2]
Currently there are two problems with the sphere brush:
* When drawing labels it's often annoying, that the brush goes to deep in the "z"-dimension. A brush that more flat would be much more useful.
* For anisotropic images the sphere brush produces elliptic results.

**Comment by imagejan** [comment]
Seeing how e.g. ilastik implemented tracing labels, I'd say that everything else but a 2D brush (as long as only a plane of the image is currently displayed) is highly counter-intuitive, even if the image data themselves are 3D.
But maybe I didn't understand you use case well enough...

**Comment by maarzt** [comment]
@frauzufall Please base your changes on branch https://github.com/maarzt/imglib2-labkit/tree/hdf5

It's now possible to give independent values for brushWidth and brushDepth:
(But currently the are hard coded to be the same value.)
see https://github.com/maarzt/imglib2-labkit/blob/a231e720f4f84d362c58dc1b2a76f32e93f311fc/src/main/java/net/imglib2/labkit/control/brush/LabelBrushController.java#L115

I think it's a good idea to have some controls in the left panel of labkit, were the use can select the ratio between brushWidth and brushHeight.
