### ISSUE TITLE
How to cite

### ISSUE THREAD

**Issue by manerotoni** [juglab/labkit-ui#86]
Hello, 
I was looking for a way to cite the software we use.
Could you add a sentence in documentation and/or README on how it is best done?
Do you have a DOI?

Antonio

**Comment by maarzt** [comment]
Citation details have been added to Labkit [github](https://github.com/juglab/labkit-ui) and [wiki](https://imagej.net/plugins/labkit) page.

@manerotoni Thanks for the hint. :+1:
