### ISSUE TITLE
Batch segmentation fails on 8-bit 3D images

### ISSUE THREAD

**Issue by damiandn** [juglab/labkit-ui#91]
OS: Windows 10
ImageJ version: 1.53q
Labkit updated to latest version

Issue:
Labkit fails when batch segmenting 8-bit 3D tiff stacks. The images can be segmented and saved individually using the GUI without issue

Steps to reproduce:
Open an image and train a classifier (I used two classes, background and foreground)
With that classifier open, select "Others  -> Batch Segment Images..."
Select an input folder (I am using a folder of 5 8-bit 3D tiff stacks, each ~65MB) and an output folder
Start batch segmentation

Expected outcome:
Batch segmentation of images, with output stored in output directory

Actual outcome:
Labkit fails to segment the images (one blank image is saved to the output folder) with following warning message:

WARNING: core mtj jar files are not available as resources to this classloader (sun.misc.Launcher$AppClassLoader@764c12b6)
net.imglib2.exception.InvalidDimensionsException: Expected only positive dimensions but got: [0, 0]java.lang.RuntimeException: Number of elements in ArrayImg too big, use for example CellImg instead: 2566914048 > 2147483647java.lang.RuntimeException: Number of elements in ArrayImg too big, use for example CellImg instead: 2246049792 > 2147483647java.lang.RuntimeException: Number of elements in ArrayImg too big, use for example CellImg instead: 2887778304 > 2147483647java.lang.RuntimeException: Number of elements in ArrayImg too big, use for example CellImg instead: 2210398208 > 2147483647net.imglib2.exception.InvalidDimensionsException: Expected only positive dimensions but got: [0, 0]java.lang.RuntimeException: Number of elements in ArrayImg too big, use for example CellImg instead: 2566914048 > 2147483647java.lang.RuntimeException: Number of elements in ArrayImg too big, use for example CellImg instead: 2246049792 > 2147483647java.lang.RuntimeException: Number of elements in ArrayImg too big, use for example CellImg instead: 2887778304 > 2147483647java.lang.RuntimeException: Number of elements in ArrayImg too big, use for example CellImg instead: 2210398208 > 2147483647[INFO] Reading available sites from https://imagej.net/

**Comment by maarzt** [comment]
Hello @damiandn, thank you for the detailed Bug report. I just uploaded a new Labkit version 0.3.7, where I completely rewrote the "Batch Segment Images..." functionality. Could you please give it a try, and report if it works now for you?

(The old "Batch Segment Images" only worked well with very small images. This problem should be fixed now.)

**Comment by damiandn** [comment]
Hello @maarzt, I can confirm that the update fixed the issue and batch segmentation works as expected now. Thanks for your quick response!
